// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUR89i6kvh3bp51GCgBX0fTwh3bFt1Ksg',
    appId: '1:631362355665:web:4d7f8eadba1bca0969e0f0',
    messagingSenderId: '631362355665',
    projectId: 'medjust-d26eb',
    authDomain: 'medjust-d26eb.firebaseapp.com',
    storageBucket: 'medjust-d26eb.firebasestorage.app',
    measurementId: 'G-VKVN9KCR87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_YU8S9rMxpewLEKLxcOYovdPmR4J20mY',
    appId: '1:631362355665:android:9c82ef6c243c495d69e0f0',
    messagingSenderId: '631362355665',
    projectId: 'medjust-d26eb',
    storageBucket: 'medjust-d26eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW1KxE7S-4Yq5O3gF7rH_lu3KSkqk5weI',
    appId: '1:631362355665:ios:2df5f01ba8e5029e69e0f0',
    messagingSenderId: '631362355665',
    projectId: 'medjust-d26eb',
    storageBucket: 'medjust-d26eb.firebasestorage.app',
    iosClientId: '631362355665-jkvjcql523gq8079414mpss9p6vrml87.apps.googleusercontent.com',
    iosBundleId: 'com.example.medJust',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW1KxE7S-4Yq5O3gF7rH_lu3KSkqk5weI',
    appId: '1:631362355665:ios:2df5f01ba8e5029e69e0f0',
    messagingSenderId: '631362355665',
    projectId: 'medjust-d26eb',
    storageBucket: 'medjust-d26eb.firebasestorage.app',
    iosClientId: '631362355665-jkvjcql523gq8079414mpss9p6vrml87.apps.googleusercontent.com',
    iosBundleId: 'com.example.medJust',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUR89i6kvh3bp51GCgBX0fTwh3bFt1Ksg',
    appId: '1:631362355665:web:c5503e0481413d9a69e0f0',
    messagingSenderId: '631362355665',
    projectId: 'medjust-d26eb',
    authDomain: 'medjust-d26eb.firebaseapp.com',
    storageBucket: 'medjust-d26eb.firebasestorage.app',
    measurementId: 'G-4RS33L41FT',
  );
}
